language: node_js

node_js:
  - "lts/*"

before_install:
  - npm install -g codecov

after_script:
  - codecov

before_deploy:
  - "echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc"
  - "echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' > .npmrc"

deploy:
  # Publish to https://registry.npmjs.org/
  - provider: script
    script: "npx lerna publish from-package --yes --registry=https://registry.npmjs.org/"
    skip_cleanup: true
    on:
      branch: master

  # Publish to https://npm.pkg.github.com/
  - provider: script
    script: "npx lerna publish from-package --yes --registry=https://npm.pkg.github.com/"
    skip_cleanup: true
    on:
      branch: master

env:
  global:
    secure: "RgMx5l16VXKAQBi19g+pGljnoFf3Jhim4HSpo8oEKVNVvBKZoM8nbh4YlsIFpBQW0bsPfoTxXM/Ekemgi2Q17737XcEgjcTIGY39NDEh1EuuTPq0zwtD7LpVzXr5Px/ketdsFVtaB0GJZQ3HIGPR784tNpgtiuNwp27t57k3Rs+pGxKpdLn5/NuziAKDUNkTTSnAuM3krgOzKIogrMXtNniOaNRNYyVgMbnep6s/Epi57blxyUiqABb8TUwooGlqgbSXKaXkIzdwjkHKcV6GTppvY6b8UfVXZHx0jskYX61Wwqc8GXHFsuJaUzJkdFL5WCUxcB/4XLDCxvOJbrkrFUJA3USz/0kWhVwo1aISlz3KscDN0cbQ5te6smqqeG43UuRY9tv/dHxl3adPelVQpIswOzsQdl0uOhkBcXkHSmPccCZgFlpE81DKdgx8OYqz6Sey3Lrvg5Hzw3DrWucF012gAiBfXBO2zJFex4ISYFnNyGRo3itPkl3c/aJO6L0sc7z6ab4nQwWIunFJVVSAmhdowX3iyJLm8u+h54HTs7EeGv+uxLQZ3rhVw7rtn+6OTs/94sajHwWphwEkWN2bBdGWrU3ZpKhkUxNLZmUPxbDbaELZVbHBEIphIrFcmZPcCUNYFkYGaM7wW/nExq4MJvv0Ngfsn5bMIMyPklepjAE="
