name: Build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build
      run: npm it

    - name: Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
        npx lerna publish from-package --yes --registry=https://registry.npmjs.org/
        npx lerna publish from-package --yes --registry=https://npm.pkg.github.com/
